<h1>Image test</h1>

<h2>Images</h2>

<a href="<?=$this->url->get(['for' => 'test-image-upload'])?>">Upload</a>

<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th scope="col">&nbsp;</th>
        <th scope="col">Code</th>
        <th scope="col">Title</th>
        <th scope="col">Type</th>
        <th scope="col">Filename</th>
        <th scope="col">Created date</th>
    </tr>
    </thead>
    <tbody>
<?php foreach ($items as $item) : ?>
        <tr>
            <th scope="row">
                <a href="<?=$this->url->get(['for' => 'test-image-edit', 'code' => $item['code']])?>">
                    <img src="<?=$item['filepath']?>" alt="<?=$item['filename']?>" title="<?=$item['filename']?>" width="100" />
                </a>
            </th>
            <th><?=$item['code']?></th>
            <td><?=$item['title']?></td>
            <td><?=$item['type_name']?></td>
            <td><?=$item['filename']?></td>
            <td><?=$item['created_date']?></td>
            <th><a class="btn btn-info btn-sm" href="<?=$this->url->get(['for' => 'test-image-edit', 'code' => $item['code']])?>">Edit</th>
            <th><a class="btn btn-danger btn-sm" href="<?=$this->url->get(['for' => 'test-image-delete', 'code' => $item['code']])?>">Delete</th>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>

<div class="row">
    <div class="col-md-12">
        <?php include $this->di->get('config')->application->viewsDir->components . 'pagination.phtml'; ?>
    </div>
</div>
