#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/app/config/scheduler.php';

$scheduler = new \GO\Scheduler();

foreach ($schedulerSettings as $command => $runAt) {
    $scheduler->php($command)->everyMinute();
}

$scheduler->run();
