<h1>FileStorage test</h1>

<h2>Upload</h2>

<form class="row g-3" action="<?=$this->url->get(['for' => 'test-filestorage-upload'])?>" method="post" enctype="multipart/form-data">

    <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input type="text" class="form-control" id="title" name="title" placeholder="Title of the file" required>
    </div>

    <div class="mb-3">
        <label for="file" class="form-label">File</label>
        <input type="file" class="form-control" id="file" name="file" placeholder="Image" required>
    </div>

    <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-3">Upload</button>
        <a href="<?=$this->url->get(['for' => 'test-filestorage-list'])?>" class="btn btn-secondary mb-3">Cancel</a>
    </div>

</form>
